apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: task-container
        image: ghcr.io/eyalvoulichman-source/task-manager:latest # האימג' שתבנה
        ports:
        - containerPort: 5000 # הפורט שהגדרנו ב-Python
        env:
        - name: APP_COLOR
          value: "lightblue"
        volumeMounts:
        - name: task-data
          mountPath: /tmp/data # הנתיב שבו האפליקציה מחפשת את הקובץ
      volumes:
      - name: task-data
        emptyDir: {} # נתחיל עם זמני, אחר כך נהפוך לקבוע