apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - name: task-container
        image: ghcr.io/eyalvoulichman-source/task-manager:latest # האימג' שתבנה
        ports:
        - containerPort: 5000 # הפורט שהגדרנו ב-Python
        env:
        - name: APP_COLOR
          value: "lightblue"
        volumeMounts:
        - name: task-data
          mountPath: /tmp/data-app # הנתיב שבו האפליקציה מחפשת את הקובץ
      volumes:
      - name: task-data
        hostPath:
          path: /run/desktop/mnt/host/d/k8s-data # כאן החלפנו מ-c ל-d
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: devops
spec:
  selector:
    app: task-app  # חשוב! זה חייב להיות בדיוק כמו ה-label ב-Deployment
  ports:
  - protocol: TCP
    port: 80       # הפורט שה-Service יקשיב לו (הכתובת ה"חיצונית")
    targetPort: 5000 # הפורט בתוך הקונטיינר (מה שרשמת ב-Python)
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tasks.local  # תוכל להוסיף כתובת חדשה ב-hosts של ווינדוס
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: task-service # השם של ה-Service שכתבנו קודם
            port:
              number: 80